import { useEffect } from 'react';
import { Alert } from 'react-bootstrap';
import SectionWrapper from '../components/SectionWrapper';
import PageHeader from '../components/PageHeader';

const PAGE_TITLE = 'About | Bias Detector';

export default function AboutPage() {
  useEffect(() => {
    const previous = document.title;
    document.title = PAGE_TITLE;
    return () => {
      document.title = previous;
    };
  }, []);

  return (
    <SectionWrapper>
      <PageHeader
        title="About"
        subtitle="What this app does, and how to interpret what you see on your screen."
      />

      <div className="text-center mx-auto mb-4" style={{ maxWidth: '44rem' }}>
        <p className="text-muted mb-0">
          Bias Detector is built to help people think critically about written content by surfacing
          potentially biased framing and offering a neutral comparison. Its purpose is to support media
          literacy, classroom discussion, and self-reflection when reading persuasive or opinion-driven
          language.
        </p>
      </div>

      <Alert variant="warning" className="mb-4 cbd-about-alert">
        <h2 className="h5 alert-heading">Artificial intelligence</h2>
        <p className="mb-0">
          The <strong>bias score</strong>, <strong>explanatory notes</strong>, and{' '}
          <strong>neutral rewrite</strong> are all <strong>generated by AI</strong>. They are
          automated estimates, not professional assessments. They can be wrong, incomplete, or
          reflect limitations of the model. Do not use this tool as a sole source of truth for
          decisions in journalism, the workplace, legal settings, or any high-stakes context.
        </p>
      </Alert>
    </SectionWrapper>
  );
}
